(ns m3.vocabulary
  (:require
   [m3.validate :refer :all]
   ))

;; TODO:
;; we need to be able to make one property depend on another - i.e. be evaluated after...
;; then we can use this to drive validation and
;; - split functions whose semantics have changed over drafts
;; - remove draft checking code from implementation

;; ultimately, this data structure needs to be reduced by the draft
;; and $vocabulary keywords and the result compiled and carried
;; around in the c2...

(def draft->vocab->property->semantics
  {"draft3"
   {:validation
    [["type"                  check-property-type]
     ["minLength"             check-property-minLength]
     ["maxLength"             check-property-maxLength]
     ["enum"                  check-property-enum]
     ["pattern"               check-property-pattern]
     ["format"                check-property-format]
     ["minProperties"         check-property-minProperties]
     ["maxProperties"         check-property-maxProperties]
     ["required"              check-property-required]
     ["minimum"               check-property-minimum]
     ["exclusiveMinimum"      check-property-exclusiveMinimum]
     ["maximum"               check-property-maximum]
     ["exclusiveMaximum"      check-property-exclusiveMaximum]
     ["minItems"              check-property-minItems]
     ["maxItems"              check-property-maxItems]
     ["uniqueItems"           check-property-uniqueItems]]
    :core
    [["$ref"                  check-property-$ref]
     ["$schema"               check-property-$schema]
     ["id"                    check-property-id]
     ["definitions"           check-property-definitions]]
    :meta-data
    [["title"                 check-property-title]
     ["description"           check-property-description]
     ["default"               check-property-default]]
    :applicator
    [["propertyDependencies"  check-property-propertyDependencies]
     ["dependencies"          check-property-dependencies]
     ["items"                 check-property-items]
     ["additionalItems"       check-property-additionalItems]
     ["properties"            check-property-properties]
     ["patternProperties"     check-property-patternProperties]
     ["additionalProperties"  check-property-additionalProperties]]}
   "draft4"
   {:validation
    [["type"                  check-property-type]
     ["minLength"             check-property-minLength]
     ["maxLength"             check-property-maxLength]
     ["multipleOf"            check-property-multipleOf]
     ["enum"                  check-property-enum]
     ["pattern"               check-property-pattern]
     ["format"                check-property-format]
     ["minProperties"         check-property-minProperties]
     ["maxProperties"         check-property-maxProperties]
     ["required"              check-property-required]
     ["minimum"               check-property-minimum]
     ["exclusiveMinimum"      check-property-exclusiveMinimum]
     ["maximum"               check-property-maximum]
     ["exclusiveMaximum"      check-property-exclusiveMaximum]
     ["minItems"              check-property-minItems]
     ["maxItems"              check-property-maxItems]
     ["uniqueItems"           check-property-uniqueItems]]
    :core
    [["$ref"                  check-property-$ref]
     ["$schema"               check-property-$schema]
     ["id"                    check-property-id]
     ["definitions"           check-property-definitions]]
    :meta-data
    [["title"                 check-property-title]
     ["description"           check-property-description]
     ["default"               check-property-default]]
    :applicator
    [["propertyDependencies"  check-property-propertyDependencies]
     ["not"                   check-property-not]
     ["anyOf"                 check-property-anyOf]
     ["oneOf"                 check-property-oneOf]
     ["allOf"                 check-property-allOf]
     ["dependencies"          check-property-dependencies]
     ["items"                 check-property-items]
     ["additionalItems"       check-property-additionalItems]
     ["properties"            check-property-properties]
     ["patternProperties"     check-property-patternProperties]
     ["additionalProperties"  check-property-additionalProperties]]}
   "draft6"
   {:validation
    [["type"                  check-property-type]
     ["const"                 check-property-const]
     ["minLength"             check-property-minLength]
     ["maxLength"             check-property-maxLength]
     ["multipleOf"            check-property-multipleOf]
     ["enum"                  check-property-enum]
     ["pattern"               check-property-pattern]
     ["format"                check-property-format]
     ["minProperties"         check-property-minProperties]
     ["maxProperties"         check-property-maxProperties]
     ["required"              check-property-required]
     ["minimum"               check-property-minimum]
     ["exclusiveMinimum"      check-property-exclusiveMinimum]
     ["maximum"               check-property-maximum]
     ["exclusiveMaximum"      check-property-exclusiveMaximum]
     ["minItems"              check-property-minItems]
     ["maxItems"              check-property-maxItems]
     ["uniqueItems"           check-property-uniqueItems]]
    :core
    [["$ref"                  check-property-$ref]
     ["$schema"               check-property-$schema]
     ["$id"                   check-property-$id]
     ["definitions"           check-property-definitions]]
    :meta-data
    [["title"                 check-property-title]
     ["description"           check-property-description]
     ["default"               check-property-default]
     ["examples"              check-property-examples]]
    :applicator
    [["propertyNames"         check-property-propertyNames]
     ["propertyDependencies"  check-property-propertyDependencies]
     ["not"                   check-property-not]
     ["anyOf"                 check-property-anyOf]
     ["oneOf"                 check-property-oneOf]
     ["allOf"                 check-property-allOf]
     ["dependencies"          check-property-dependencies]
     ["contains"              check-property-contains]
     ["items"                 check-property-items]
     ["additionalItems"       check-property-additionalItems]
     ["properties"            check-property-properties]
     ["patternProperties"     check-property-patternProperties]
     ["additionalProperties"  check-property-additionalProperties]]}
   "draft7"
   {:validation
    [["type"                  check-property-type]
     ["const"                 check-property-const]
     ["minLength"             check-property-minLength]
     ["maxLength"             check-property-maxLength]
     ["multipleOf"            check-property-multipleOf]
     ["enum"                  check-property-enum]
     ["pattern"               check-property-pattern]
     ["format"                check-property-format]
     ["minProperties"         check-property-minProperties]
     ["maxProperties"         check-property-maxProperties]
     ["required"              check-property-required]
     ["minimum"               check-property-minimum]
     ["exclusiveMinimum"      check-property-exclusiveMinimum]
     ["maximum"               check-property-maximum]
     ["exclusiveMaximum"      check-property-exclusiveMaximum]
     ["minItems"              check-property-minItems]
     ["maxItems"              check-property-maxItems]
     ["uniqueItems"           check-property-uniqueItems]]
    :core
    [["$ref"                  check-property-$ref]
     ["$schema"               check-property-$schema]
     ["$id"                   check-property-$id]
     ["definitions"           check-property-definitions]]
    :meta-data
    [["title"                 check-property-title]
     ["description"           check-property-description]
     ["default"               check-property-default]
     ["examples"              check-property-examples]
     ["readOnly"              check-property-readOnly]
     ["writeOnly"             check-property-writeOnly]]
    :applicator
    [["propertyNames"         check-property-propertyNames]
     ["propertyDependencies"  check-property-propertyDependencies]
     ["not"                   check-property-not]
     ["anyOf"                 check-property-anyOf]
     ["oneOf"                 check-property-oneOf]
     ["allOf"                 check-property-allOf]
     ["dependencies"          check-property-dependencies]
     ["contains"              check-property-contains]
     ["if"                    check-property-if]
     ["then"                  check-property-then]
     ["else"                  check-property-else]
     ["items"                 check-property-items]
     ["additionalItems"       check-property-additionalItems]
     ["properties"            check-property-properties]
     ["patternProperties"     check-property-patternProperties]
     ["additionalProperties"  check-property-additionalProperties]]
    :content
    [["contentEncoding"       check-property-contentEncoding]
     ["contentMediaType"      check-property-contentMediaType]]}
   "draft2019-09"
   {:validation
    [["type"                  check-property-type]
     ["const"                 check-property-const]
     ["minLength"             check-property-minLength]
     ["maxLength"             check-property-maxLength]
     ["multipleOf"            check-property-multipleOf]
     ["enum"                  check-property-enum]
     ["pattern"               check-property-pattern]
     ["format"                check-property-format]
     ["dependentRequired"     check-property-dependentRequired]
     ["minProperties"         check-property-minProperties]
     ["maxProperties"         check-property-maxProperties]
     ["required"              check-property-required]
     ["minimum"               check-property-minimum]
     ["exclusiveMinimum"      check-property-exclusiveMinimum]
     ["maximum"               check-property-maximum]
     ["exclusiveMaximum"      check-property-exclusiveMaximum]
     ["minItems"              check-property-minItems]
     ["maxItems"              check-property-maxItems]
     ["uniqueItems"           check-property-uniqueItems]]
    :core
    [["$ref"                  check-property-$ref]
     ["$schema"               check-property-$schema]
     ["$id"                   check-property-$id]
     ["$anchor"               check-property-$anchor]
     ["$recursiveRef"         check-property-$recursiveRef]
     ["$recursiveAnchor"      check-property-$recursiveAnchor]
     ["$vocabulary"           check-property-$vocabulary]
     ["$comment"              check-property-$comment]
     ["$defs"                 check-property-$defs]]
    :meta-data
    [["title"                 check-property-title]
     ["description"           check-property-description]
     ["default"               check-property-default]
     ["examples"              check-property-examples]
     ["readOnly"              check-property-readOnly]
     ["writeOnly"             check-property-writeOnly]]
    :applicator
    [["propertyNames"         check-property-propertyNames]
     ["not"                   check-property-not]
     ["anyOf"                 check-property-anyOf]
     ["oneOf"                 check-property-oneOf]
     ["allOf"                 check-property-allOf]
     ["dependentSchemas"      check-property-dependentSchemas]
     ["contains"              check-property-contains]
     ["if"                    check-property-if]
     ["then"                  check-property-then]
     ["else"                  check-property-else]
     ["items"                 check-property-items]
     ["additionalItems"       check-property-additionalItems]
     ["properties"            check-property-properties]
     ["patternProperties"     check-property-patternProperties]
     ["additionalProperties"  check-property-additionalProperties]]
    :content
    [["contentEncoding"       check-property-contentEncoding]
     ["contentMediaType"      check-property-contentMediaType]]
    :unevaluated
    [["unevaluatedItems"      check-property-unevaluatedItems]
     ["unevaluatedProperties" check-property-unevaluatedProperties]]}
   "draft2020-12"
   {:validation
    [["type"                  check-property-type]
     ["const"                 check-property-const]
     ["minLength"             check-property-minLength]
     ["maxLength"             check-property-maxLength]
     ["multipleOf"            check-property-multipleOf]
     ["enum"                  check-property-enum]
     ["pattern"               check-property-pattern]
     ["dependentRequired"     check-property-dependentRequired]
     ["minContains"           check-property-minContains]
     ["maxContains"           check-property-maxContains]
     ["minProperties"         check-property-minProperties]
     ["maxProperties"         check-property-maxProperties]
     ["required"              check-property-required]
     ["minimum"               check-property-minimum]
     ["exclusiveMinimum"      check-property-exclusiveMinimum]
     ["maximum"               check-property-maximum]
     ["exclusiveMaximum"      check-property-exclusiveMaximum]
     ["minItems"              check-property-minItems]
     ["maxItems"              check-property-maxItems]
     ["uniqueItems"           check-property-uniqueItems]]
    :core
    [["$ref"                  check-property-$ref]
     ["$schema"               check-property-$schema]
     ["$id"                   check-property-$id]
     ["$anchor"               check-property-$anchor]
     ["$dynamicRef"           check-property-$dynamicRef]
     ["$dynamicAnchor"        check-property-$dynamicAnchor]
     ["$vocabulary"           check-property-$vocabulary]
     ["$comment"              check-property-$comment]
     ["$defs"                 check-property-$defs]]
    :meta-data
    [["title"                 check-property-title]
     ["description"           check-property-description]
     ["default"               check-property-default]
     ["examples"              check-property-examples]
     ["deprecated"            check-property-deprecated]
     ["readOnly"              check-property-readOnly]
     ["writeOnly"             check-property-writeOnly]]
    :applicator
    [["propertyNames"         check-property-propertyNames]
     ["not"                   check-property-not]
     ["anyOf"                 check-property-anyOf]
     ["oneOf"                 check-property-oneOf]
     ["allOf"                 check-property-allOf]
     ["dependentSchemas"      check-property-dependentSchemas]
     ["contains"              check-property-contains]
     ["if"                    check-property-if]
     ["then"                  check-property-then]
     ["else"                  check-property-else]
     ["prefixItems"           check-property-prefixItems]
     ["items"                 check-property-items]
     ["properties"            check-property-properties]
     ["patternProperties"     check-property-patternProperties]
     ["additionalProperties"  check-property-additionalProperties]]
    :content
    [["contentEncoding"       check-property-contentEncoding]
     ["contentMediaType"      check-property-contentMediaType]
     ["contentSchema"         check-property-contentSchema]]
    :unevaluated
    [["unevaluatedItems"      check-property-unevaluatedItems]
     ["unevaluatedProperties" check-property-unevaluatedProperties]]
    :format-assertion
    [["format"                check-property-format]]}
   "draft2021-12"
   {:validation
    [["type"                  check-property-type]
     ["const"                 check-property-const]
     ["minLength"             check-property-minLength]
     ["maxLength"             check-property-maxLength]
     ["multipleOf"            check-property-multipleOf]
     ["enum"                  check-property-enum]
     ["pattern"               check-property-pattern]
     ["dependentRequired"     check-property-dependentRequired]
     ["minContains"           check-property-minContains]
     ["maxContains"           check-property-maxContains]
     ["minProperties"         check-property-minProperties]
     ["maxProperties"         check-property-maxProperties]
     ["required"              check-property-required]
     ["minimum"               check-property-minimum]
     ["exclusiveMinimum"      check-property-exclusiveMinimum]
     ["maximum"               check-property-maximum]
     ["exclusiveMaximum"      check-property-exclusiveMaximum]
     ["minItems"              check-property-minItems]
     ["maxItems"              check-property-maxItems]
     ["uniqueItems"           check-property-uniqueItems]]
    :core
    [["$ref"                  check-property-$ref]
     ["$schema"               check-property-$schema]
     ["$id"                   check-property-$id]
     ["$anchor"               check-property-$anchor]
     ["$dynamicRef"           check-property-$dynamicRef]
     ["$dynamicAnchor"        check-property-$dynamicAnchor]
     ["$vocabulary"           check-property-$vocabulary]
     ["$comment"              check-property-$comment]
     ["$defs"                 check-property-$defs]]
    :meta-data
    [["title"                 check-property-title]
     ["description"           check-property-description]
     ["default"               check-property-default]
     ["examples"              check-property-examples]
     ["deprecated"            check-property-deprecated]
     ["readOnly"              check-property-readOnly]
     ["writeOnly"             check-property-writeOnly]]
    :applicator
    [["propertyNames"         check-property-propertyNames]
     ["not"                   check-property-not]
     ["anyOf"                 check-property-anyOf]
     ["oneOf"                 check-property-oneOf]
     ["allOf"                 check-property-allOf]
     ["dependentSchemas"      check-property-dependentSchemas]
     ["contains"              check-property-contains]
     ["if"                    check-property-if]
     ["then"                  check-property-then]
     ["else"                  check-property-else]
     ["prefixItems"           check-property-prefixItems]
     ["items"                 check-property-items]
     ["properties"            check-property-properties]
     ["patternProperties"     check-property-patternProperties]
     ["additionalProperties"  check-property-additionalProperties]]
    :content
    [["contentEncoding"       check-property-contentEncoding]
     ["contentMediaType"      check-property-contentMediaType]
     ["contentSchema"         check-property-contentSchema]]
    :unevaluated
    [["unevaluatedItems"      check-property-unevaluatedItems]
     ["unevaluatedProperties" check-property-unevaluatedProperties]]
    :format-assertion
    [["format"                check-property-format]]}})
